name: My reminders workflow

# Controls when the action will run. 
on:
  # Triggers the workflow to run at 19:00 UTC on the 1st of every month
  schedule:
  - cron: "0 19 1 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "cron-job-reminders"
  cron-job-reminders:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Invoke my reminders api endpoint deployed at Vercel
        run: |
          echo "Invoke here the API"
          echo "My job is done!"
